services:
  memcached:
    image: memcached:1.6.12
    ports:
      - "11211:11211"

  mongodb:
    image: mongo:4.4-focal
    command: mongod
    volumes:
      - ~/data/db.logjamdb1b:/data/db
    ports:
      - "27017:27017"

  testdb:
    image: mongo:4.4-focal
    command: mongod
    volumes:
      - ~/data/db.testdb1:/data/db
    ports:
      - "27018:27017"
