mongodb: runsv /etc/service/mongodb
memcached: runsv /etc/service/memcached
importer: runsv /home/logjam/logjam_app/service/cimporter
livestream: runsv /home/logjam/logjam_app/service/live-stream-development
web: runsv /etc/service/rails
