name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Start containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1

      - name: Install system packages
        run: sudo apt-get install build-essential zlib1g-dev nodejs libssl-dev libzmq3-dev

      - name: Install yarn
        run: sudo npm install yarn

      - name: Install node packages
        run: yarn install

      - name: Install gems
        run: bundle install

      - name: Run tests
        run: bundle exec rake

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down
